Development2
PrinceBadru/math-magicians pull request #4
Opened 2023-09-19 09:20 UTC by PrinceBadru

## Math Magicians: Components
- Delete all the boilerplate from Create React App (text, images, styles).
- Create a new directory called components.
- Inside components, create a new Calculator.js file.
- In Calculator.js, create a React component that matches the design

2023-09-22 07:27 UTC, TedLivist reviewed
## STATUS: INVALID CODE REVIEW REQUEST 🛑 🛑

Hi @PrinceBadru,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

### If you have no live demo then kindly remove its section and its link on the table of headers.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-22 14:31 UTC, zeff96 reviewed
Hi <STUDENT_MENTION>, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- [ ] Hello, Kindly, as mentioned by the previous reviewer, your project has not been deployed yet. Please consider removing the "Live Demo" header link from the table of contents. ✏️

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-09-22 20:01 UTC, VICTOR-CHUKWU requested changes
Hi @PrinceBadru  👋  

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![almost](https://media.giphy.com/media/R2m2NzVxQ3pbG/giphy.gif)

## Highlights
- Good PR
- Good commit
- All linters passed
- app created correctly


## Required Changes ♻️

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-22 20:01 UTC, VICTOR-CHUKWU commented on public/manifest.json
> +}
- [ ] I am making the comment here but it also includes other files. Kindly make sure that all boilerplate files created while creating the react app have been removed files like
```
favicon.io
logo192.png
logo512.png
robot.txt
App.tsest.js
reportwebvitals.js
setupTests.js
and also this file where I made the comment
```

2023-09-22 20:01 UTC, VICTOR-CHUKWU commented on README.md
> +This project is [MIT](./MIT.md) licensed.
- [ ] your MIT link is broken, kindly fix it

2023-09-23 05:49 UTC, tufoinnkuo10 approved these changes
## Status: Approved :heavy_check_mark:

Hi @PrinceBadru 

Your project is complete! Great job for making the requested changes 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Components ok
- No linter errors


----[optional] kindly remember to use the correct git flow in your coming projects. Read [here ](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md)to learn how to do that
<br>
Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-23 05:51 UTC, merged

2023-10-19 08:25 UTC, zeff96 reviewed
## STATUS: INVALID CODE REVIEW 🛑
Hi @PrinceBadru , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

Hello @PrinceBadru, 🚨 Please take note that the milestone you've submitted for review is not the correct one. 🙅‍♂️ You were supposed to submit the milestone for Events, but regrettably, you've submitted the milestone for Components instead. 🤔 Please review your submission and ensure you submit the correct milestone for Events. 📆🔍 Thank you! 😊

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._