Full website
PrinceBadru/math-magicians pull request #7
Opened 2023-09-28 13:42 UTC by PrinceBadru

## Magicians : Full Website.
- Create a website consisting of 3 pages: Home, Calculator, and Quote.
- Add your own styles to improve the look and feel.
- Use React basic styling (inline styles, importing CSS and pre-processed CSS files).
- For every page, you should create a <Route>.
- Make sure that navigation links for all 3 routes are displayed on each page.
- Use [React Router](https://reactrouter.com/) to make the routes work.

2023-09-28 14:13 UTC, gemmen29 requested changes
Hi @PrinceBadru, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights 💯 
- No linters errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 

## Required Changes ♻️
_Check the comments under the review._

![](https://media.giphy.com/media/tKyrc0NTlEcGWdThp4/giphy.gif)

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-28 14:13 UTC, gemmen29 commented on src/App.js
> +      <div className="App">
- [ ] Kindly fix this error:
![image](https://github.com/PrinceBadru/math-magicians/assets/24703171/c307148f-bfed-497c-b9e6-cdacfd0ba2ac)
When I run your project I get this error.

2023-09-28 19:18 UTC, Bantealem approved these changes
# Status: Approved ![approved](https://github.com/PrinceBadru/math-magicians/assets/101523582/332b0e30-9291-4998-858a-efa6545ed419)

Hi @PrinceBadru, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![Screenshot from 2023-09-27 20-56-29](https://github.com/PrinceBadru/math-magicians/assets/101523582/2083cd24-2806-406a-897d-b9d85d76e658)


## Highlights
- [x] Correct Git flow
- [x] Professional Readme
- [x] No Linters error
- [x] Descriptive Readme
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-29 19:19 UTC, merged

2023-10-24 21:04 UTC, Felix45 reviewed
# Approved :green_circle: 
Hi @PrinceBadru, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

<img src="https://user-images.githubusercontent.com/38088818/253566971-43d45e44-98b5-4608-a589-53a38ffb3ea1.gif" width="350px" />

## Highlights :heavy_check_mark: 
- [x] Good UI design :white_check_mark: 
- [x] Application functions as expected :white_check_mark: 
- [x] Git flow is used correctly :white_check_mark:  
- [x] Repository has a professional readme file :white_check_mark: 
- [x] Pull request has a descriptive readme file :white_check_mark:    

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._